version: '3'

services:
  web:
    image: "${IMAGE}"
  db:
    container_name: chatty-db
    image: mongo:latest
    restart: always
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume: